import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.scss";
import Header from "@/components/web/header/Header";
import Footer1 from "@/components/web/footer/Footer";
import Footer from "../Shared/Footer/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: { default: "EaseMySailing", template: "%s | EaseMySailing" },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="w-full h-screen flex flex-col">
          <Header />
          {children}
          <Footer1 />
          <Footer/>
        </main>
      </body>
    </html>
  );
}
