"use client";
import { useState } from "react";
import Head from "next/head";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "../globals.scss";
import Header from "@/components/web/header/Header";
import Footer1 from "@/components/web/footer/Footer";
import Footer from "../Shared/Footer/Footer";
import DisableRightClick from "@/components/web/disablerightclick/DisableRightClick";
// import Footer from "@/components/web/footer/Footer";
import PinPopup from "@/components/web/secruity_code/Pinpopup";

// export const metadata: Metadata = {
//   title: { default: "EaseMySailing", template: "%s | EaseMySailing" },
//   description: "Generated by create next app",
// };
const poppins = Poppins({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [showPopup, setShowPopup] = useState(true); // Control visibility of the popup

  const closeModal = () => {
    setShowPopup(false); // Close the popup
  };
  return (
    <html lang="en">
      <body className={poppins.className}>
        <main className="w-full h-screen flex flex-col">
          {/* {showPopup ? (
            <PinPopup closeModal={closeModal} />
          ) : ( */}
          <>
            {/* <DisableRightClick /> */}

            <Header />

            {children}
            <Footer1 />
            <Footer />
          </>
          {/* )}  */}
        </main>
      </body>
    </html>
  );
}
