export default{
    GETPROFILE:'/v1/profile',
    PUTPROFILE:'/v1/profile',
    GETENUMS:'/v1/enums',
    POSTMYJOB:'/api/job-requirements',
    GETMYJOB:'/api/job-requirements',
    POSTNEXTOF:'/api/next-of-kin-details',
    POSTLANGUAGE:'/api/v1/languages',
    POSTABOUTME:'/api/v1/aboutme',
    POSTECDIS:'/api/v1/ecdis-training',
    POSTMEDICAL:'/api/v1/medical-certificates',
    POSTONLINEPRASENCE:'/api/online-presence',
    POSTLICENSES:'/api/v1/licenses',
    POSTCONTACT:'/api/v1/contact-details',
    POSTSEADETAILS: '/api/v1/offshore-requirements',
    POSTSEAGOING: '/api/v1/seagoing-experiences',
    POSTTRAVELDOCUMENT:'/api/v1/travel-documents',
    POSTSTCWTRAINING:'/api/v1/stcw-training',
    POSTPROFESSIONALSKILL:'/api/v1/professional-skills',
    POSTREFERENCE:'/api/v1/references',
}