export default{
    GETPROFILE:'/v1/profile',
    PUTPROFILE:'/v1/profile',
    GETENUMS:'/v1/enums',
    POSTMYJOB:'/api/job-requirements',
    GETMYJOB:'/api/job-requirements',
    POSTNEXTOF:'/api/next-of-kin-details',
    GETNEXTOF:'/api/next-of-kin-details',
    POSTLANGUAGE:'/api/v1/languages',
    GETLANGUAGE:'/api/v1/languages',
    POSTABOUTME:'/api/v1/aboutme',
    GETABOUTME:'/api/v1/aboutme',
    POSTECDIS:'/api/v1/ecdis-training',
    GETECDIS:'/api/v1/ecdis-training',
    POSTMEDICAL:'/api/medicalCertificates',
    GETMEDICAL:'/api/medicalCertificates',
    POSTONLINEPRASENCE:'/api/online-presence',
    GETONLINEPRASENCE:'/api/online-presence',
    POSTLICENSES:'/api/v1/licenses',
    GETLICENSES:'/api/v1/licenses',
    POSTCONTACT:'/api/v1/contact-details',
    GETCONTACT:'/api/v1/contact-details',
    POSTSEADETAILS: '/api/v1/offshore-requirements',
    GETSEADETAILS: '/api/v1/offshore-requirements',
    POSTSEAGOING: '/api/v1/seagoing-experiences',
    GETSEAGOING: '/api/v1/seagoing-experiences',
    POSTTRAVELDOCUMENT:'/api/travelDocuments',
    GETTRAVELDOCUMENT:'/api/travelDocuments',
    POSTSTCWTRAINING:'/api/stcwTrainings',
    GETSTCWTRAINING:'/api/stcwTrainings',
    POSTPROFESSIONALSKILL:'/api/v1/professional-skills',
    GETPROFESSIONALSKILL:'/api/v1/professional-skills',
    POSTREFERENCE:'/api/v1/references',
    GETREFERENCE:'/api/v1/references',
    POSTADDITIIONAL:'/api/additionalTraining',
    GETADDITIIONAL:'/api/additionalTraining',
    POSTVETTING:'/api/v1/vetting-services',
    GETVETTING:'/api/v1/vetting-services',
    POSTACADEMIC:'/api/educationDetails',
    GETACADEMIC:'/api/educationDetails',
    POSTSHOREJOB:'/api/shorejobs',
    GETSHOREJOB:'/api/shorejobs'
}